### ISSUE TITLE
error loading license key

### ISSUE THREAD

**Issue by mgrabmair** [pointslope/docker-datomic-example#5]
Hi,

I am following the instructions exactly (including adding the license key as stated), but I cannot get the db to work. Is there any way to tell what's wrong? Thanks.

```
Attaching to dockerdatomicexample_datomicdb_1, dockerdatomicexample_waiter_1, dockerdatomicexample_console_1
datomicdb_1 | Launching with Java options -server -Xms1g -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=50
console_1   | Console started on port: 9000
console_1   |    dev = datomic:dev://datomicdb:4334
console_1   | Open http://localhost:9000/browse in your browser (Chrome recommended)
waiter_1    | waiting for TCP connection to 172.17.0.2
waiter_1    | 172.17.0.2
waiter_1    | 172.17.0.2
waiter_1    | 172.17.0.2
waiter_1    | 172.17.0.2
waiter_1    | 172.17.0.2
waiter_1    | 172.17.0.2
waiter_1    | 172.17.0.2
waiter_1    | 172.17.0.2:4336
waiter_1    | 4336
waiter_1    | 4334
waiter_1    | 4334
Press ENTER or type command to continue
waiter_1    | 4335
waiter_1    | 4335
waiter_1    | 4336
waiter_1    | 4336
waiter_1    | 4334
waiter_1    | 4334
waiter_1    | 4336
waiter_1    | 4334
waiter_1    | 4334
waiter_1    | 4335
datomicdb_1 | Critical failure, cannot continue: Error starting transactor
datomicdb_1 | java.lang.RuntimeException: Unable to load license key*
datomicdb_1 |   at datomic.transactor_ext$start_pro$fn__19600.invoke(transactor_ext.clj:42)
datomicdb_1 |   at datomic.transactor_ext$start_pro.invoke(transactor_ext.clj:42)
datomicdb_1 |   at clojure.lang.Var.invoke(Var.java:379)
datomicdb_1 |   at datomic.transactor$run_STAR_.invoke(transactor.clj:289)
datomicdb_1 |   at datomic.transactor$run$fn__19720.invoke(transactor.clj:338)
datomicdb_1 |   at clojure.core$binding_conveyor_fn$fn__4444.invoke(core.clj:1916)
datomicdb_1 |   at clojure.lang.AFn.call(AFn.java:18)
datomicdb_1 |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
datomicdb_1 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
datomicdb_1 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
datomicdb_1 |   at java.lang.Thread.run(Thread.java:745)
dockerdatomicexample_datomicdb_1 exited with code 255
```

**Comment by christianromney** [comment]
mgrabmair,

Don't know if you got this working or even need it working anymore, but I'd encourage you to try the latest version. Seems to work fine for me, but I'd be happy to try helping you troubleshoot.

**Comment by christianromney** [comment]
@mgrabmair Is this still an issue for you?

**Comment by mgrabmair** [comment]
Thanks for picking this up again.

I got sidetracked on another project but will have to address this sooner or later again. I will give it another try using the latest version over the next few days and get back to you here.

**Comment by dazld** [comment]
I'm having this same issue.

```
console_1    | Console started on port: 9000
console_1    |    dev = datomic:dev://datomicdb:4334
console_1    | Open http://localhost:9000/browse in your browser (Chrome recommended)
datomicdb_1  | Critical failure, cannot continue: Error starting transactor
datomicdb_1  | java.lang.RuntimeException: Unable to load license key*
datomicdb_1  |  at datomic.transactor_ext$start_pro$fn__19609.invoke(transactor_ext.clj:42)
datomicdb_1  |  at datomic.transactor_ext$start_pro.invokeStatic(transactor_ext.clj:42)
datomicdb_1  |  at datomic.transactor_ext$start_pro.invoke(transactor_ext.clj:38)
datomicdb_1  |  at clojure.lang.Var.invoke(Var.java:379)
datomicdb_1  |  at datomic.transactor$run_STAR_.invokeStatic(transactor.clj:289)
datomicdb_1  |  at datomic.transactor$run_STAR_.invoke(transactor.clj:216)
datomicdb_1  |  at datomic.transactor$run$fn__19729.invoke(transactor.clj:338)
datomicdb_1  |  at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
datomicdb_1  |  at clojure.lang.AFn.call(AFn.java:18)
datomicdb_1  |  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
datomicdb_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
datomicdb_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
datomicdb_1  |  at java.lang.Thread.run(Thread.java:745)
```

**Comment by christianromney** [comment]
did you edit the .credentials file in both the datomic-pro-starter and datomic-console directories?

**Comment by dazld** [comment]
yes, and added the license key to `dev-transactor.properties`

**Comment by dazld** [comment]
ok, got it - the license key has to be on one line, all working ok. suspect @mgrabmair had same issue!

**Comment by GradySimon** [comment]
@dazld - would you mind explaining more what you mean by "the license key has to be on one line"? I am hitting this error, and I'm not sure how to apply your advice.

**Comment by dazld** [comment]
@GradySimon exactly this - make sure your license key is not split across multiple lines (i.e., no line breaks in the middle of it). does that help?
